version: "3"

services:
  db:
    image: mariadb:10
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      # - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .db.env
    environment:
      TZ: Asia/Seoul
    # networks:
    #   - backend
    restart: always

# networks:
#   backend: